#!/usr/bin/env python3
"""Build a translation manifest for the Vietnamese OI Public Library fork."""

from __future__ import annotations

import csv
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
VI = ROOT / "vi"
OUT = VI / "MANIFEST.md"
TODO = VI / "TODO.md"
TRACKED_EXTS = {
    ".pdf": "pdf",
    ".doc": "doc",
    ".docx": "docx",
    ".ppt": "ppt",
    ".pptx": "pptx",
    ".rtf": "rtf",
    ".md": "md",
}
SKIP_PREFIXES = ("vi/", ".git/")


def git_files() -> list[str]:
    raw = subprocess.check_output(["git", "ls-files", "-z"], cwd=ROOT)
    return [p for p in raw.decode("utf-8", errors="replace").split("\0") if p]


def page_count(path: str) -> str:
    if not path.lower().endswith(".pdf"):
        return ""
    try:
        out = subprocess.check_output(
            ["pdfinfo", path],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "?"
    match = re.search(r"^Pages:\s+(\d+)", out, re.MULTILINE)
    return match.group(1) if match else "?"


def translated_sources() -> dict[str, str]:
    result: dict[str, str] = {}
    pattern = re.compile(r"^%\s+Source-(?:PDF|File):\s+(.+?)\s*$", re.MULTILINE)
    for tex in sorted((VI / "sources").glob("**/*.tex")):
        text = tex.read_text(encoding="utf-8", errors="replace")
        for match in pattern.finditer(text):
            result[match.group(1)] = str(tex.relative_to(ROOT))
    return result


def rows() -> list[dict[str, str]]:
    translated = translated_sources()
    data: list[dict[str, str]] = []
    for path in git_files():
        if path.startswith(SKIP_PREFIXES):
            continue
        ext = Path(path).suffix.lower()
        kind = TRACKED_EXTS.get(ext)
        if not kind:
            continue
        data.append(
            {
                "status": "translated" if path in translated else "todo",
                "kind": kind,
                "pages": page_count(path),
                "source": path,
                "translation": translated.get(path, ""),
            }
        )
    data.sort(key=lambda r: (r["status"] != "todo", r["kind"], r["source"]))
    return data


def write_manifest(data: list[dict[str, str]]) -> None:
    counts: dict[str, int] = {}
    for row in data:
        counts[row["kind"]] = counts.get(row["kind"], 0) + 1
    translated = sum(1 for row in data if row["status"] == "translated")

    lines = [
        "# Vietnamese Translation Manifest",
        "",
        "Generated by `vi/tools/build_manifest.py`.",
        "",
        f"- Tracked source documents: {len(data)}",
        f"- Translated documents: {translated}",
        f"- Remaining documents: {len(data) - translated}",
        "",
        "## Counts By Type",
        "",
        "| Type | Count |",
        "| --- | ---: |",
    ]
    for kind in sorted(counts):
        lines.append(f"| {kind} | {counts[kind]} |")

    lines.extend(
        [
            "",
            "## Documents",
            "",
            "| Status | Type | Pages | Source | Translation |",
            "| --- | --- | ---: | --- | --- |",
        ]
    )
    for row in data:
        lines.append(
            "| {status} | {kind} | {pages} | `{source}` | {translation} |".format(
                status=row["status"],
                kind=row["kind"],
                pages=row["pages"],
                source=row["source"].replace("|", r"\|"),
                translation=f"`{row['translation']}`" if row["translation"] else "",
            )
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    csv_path = VI / "MANIFEST.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["status", "kind", "pages", "source", "translation"])
        writer.writeheader()
        writer.writerows(data)

    short_pdfs = [
        row
        for row in data
        if row["status"] == "todo"
        and row["kind"] == "pdf"
        and row["pages"].isdigit()
        and int(row["pages"]) <= 10
    ]
    short_pdfs.sort(key=lambda r: (int(r["pages"]), r["source"]))

    todo_lines = [
        "# Translation Work Queue",
        "",
        "Generated by `vi/tools/build_manifest.py`.",
        "",
        "Quality issues for files that already have a LaTeX translation are tracked",
        "separately in `QUALITY_AUDIT.md`.",
        "",
        "## Short PDF-first Queue",
        "",
        "These PDF-only documents are at most 10 pages and are good candidates for",
        "parallel subagent translation.",
        "",
        "| Pages | Source |",
        "| ---: | --- |",
    ]
    for row in short_pdfs:
        todo_lines.append(f"| {row['pages']} | `{row['source'].replace('|', r'\|')}` |")

    TODO.write_text("\n".join(todo_lines) + "\n", encoding="utf-8")


def main() -> None:
    write_manifest(rows())


if __name__ == "__main__":
    main()
