#!/usr/bin/env python3
"""Build an article-level worklist for long collection translations."""

from __future__ import annotations

import re
from pathlib import Path


VI = Path(__file__).resolve().parents[1]
OUT = VI / "QUALITY_WORKLIST.md"
COLLECTIONS = sorted((VI / "sources" / "ioi").glob("*national-training-team-collection.tex"))


def strip_latex(text: str) -> str:
    text = re.sub(r"\\emph\{([^{}]*)\}", r"\1", text)
    text = re.sub(r"\\\((.*?)\\\)", r"\1", text)
    text = re.sub(r"\\[a-zA-Z]+\*?(?:\[[^\]]*\])?", "", text)
    text = text.replace("{", "").replace("}", "")
    return " ".join(text.split())


def toc_rows(text: str) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for line in text.splitlines():
        if "&" not in line or not line.rstrip().endswith("\\\\"):
            continue
        if line.strip().startswith(r"\textbf"):
            continue
        parts = [part.strip().rstrip("\\").strip() for part in line.split("&")]
        if len(parts) >= 3 and parts[0].isdigit():
            rows.append((parts[0], parts[1], parts[2]))
    return rows


def body_after_toc(text: str) -> str:
    marker = r"\end{center}"
    pos = text.find(marker)
    return text[pos + len(marker) :] if pos != -1 else text


def article_started(title: str, body: str) -> bool:
    plain = strip_latex(title)
    if not plain:
        return False
    return plain in strip_latex(body)


def main() -> None:
    lines = [
        "# Article Translation Worklist",
        "",
        "Generated by `vi/tools/build_quality_worklist.py`.",
        "",
        "This file tracks long annual collection PDFs at article granularity. Status",
        "is heuristic: `started` means the article title appears again outside the",
        "translated ToC; `todo` means the file appears to have only the ToC entry.",
        "",
    ]
    total = started = 0
    for path in COLLECTIONS:
        text = path.read_text(encoding="utf-8", errors="replace")
        rows = toc_rows(text)
        if not rows:
            continue
        rel = path.relative_to(VI)
        lines.extend(
            [
                f"## {path.stem.replace('-national-training-team-collection', '')}",
                "",
                f"Source translation: `{rel}`",
                "",
                "| Status | Page | Article | Author |",
                "| --- | ---: | --- | --- |",
            ]
        )
        body = body_after_toc(text)
        for page, title, author in rows:
            status = "started" if article_started(title, body) else "todo"
            total += 1
            started += status == "started"
            lines.append(f"| {status} | {page} | {title} | {author} |")
        lines.append("")
    lines.insert(4, f"- Articles started: {started}")
    lines.insert(5, f"- Articles total: {total}")
    lines.insert(6, "")
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
