#!/usr/bin/env python3
"""Build an article-level worklist for long collection translations."""

from __future__ import annotations

import re
from pathlib import Path


VI = Path(__file__).resolve().parents[1]
OUT = VI / "QUALITY_WORKLIST.md"
COLLECTIONS = sorted((VI / "sources" / "ioi").glob("*national-training-team-collection.tex"))


def strip_latex(text: str) -> str:
    text = re.sub(r"\\emph\{([^{}]*)\}", r"\1", text)
    text = re.sub(r"\\\((.*?)\\\)", r"\1", text)
    text = re.sub(r"\\[a-zA-Z]+\*?(?:\[[^\]]*\])?", "", text)
    text = text.replace("{", "").replace("}", "")
    return " ".join(text.split())


def braced_argument(text: str, open_brace: int) -> tuple[str, int] | None:
    if open_brace >= len(text) or text[open_brace] != "{":
        return None
    depth = 0
    for pos in range(open_brace, len(text)):
        char = text[pos]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace + 1 : pos], pos + 1
    return None


def section_titles(text: str) -> list[str]:
    titles: list[str] = []
    for match in re.finditer(r"\\section\*?", text):
        pos = match.end()
        while pos < len(text) and text[pos].isspace():
            pos += 1
        if pos < len(text) and text[pos] == "[":
            close = text.find("]", pos)
            if close == -1:
                continue
            pos = close + 1
            while pos < len(text) and text[pos].isspace():
                pos += 1
        arg = braced_argument(text, pos)
        if arg is not None:
            titles.append(strip_latex(arg[0]))
    return titles


def toc_rows(text: str) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for line in text.splitlines():
        if "&" not in line or not line.rstrip().endswith("\\\\"):
            continue
        if line.strip().startswith(r"\textbf"):
            continue
        parts = [part.strip().rstrip("\\").strip() for part in line.split("&")]
        if len(parts) >= 3 and parts[0].isdigit():
            rows.append((parts[0], parts[1], parts[2]))
    return rows


def toc_block(text: str) -> tuple[str, int]:
    section = r"\section{Mục lục đã dịch}"
    start = text.find(section)
    if start == -1:
        start = 0
    begin = text.find(r"\begin{center}", start)
    if begin == -1:
        return text, 0
    end_marker = r"\end{center}"
    end = text.find(end_marker, begin)
    if end == -1:
        return text[begin:], begin
    return text[begin : end + len(end_marker)], end + len(end_marker)


def body_after_toc(text: str) -> str:
    _, end = toc_block(text)
    return text[end:] if end else text


def article_started(title: str, body: str) -> bool:
    plain = strip_latex(title)
    if not plain:
        return False
    return any(plain == heading or plain in heading for heading in section_titles(body))


def main() -> None:
    lines = [
        "# Article Translation Worklist",
        "",
        "Generated by `vi/tools/build_quality_worklist.py`.",
        "",
        "This file tracks long annual collection PDFs at article granularity. Status",
        "is heuristic: `started` means the article title appears again outside the",
        "translated ToC; `todo` means the file appears to have only the ToC entry.",
        "",
    ]
    total = started = 0
    for path in COLLECTIONS:
        text = path.read_text(encoding="utf-8", errors="replace")
        rows = toc_rows(toc_block(text)[0])
        if not rows:
            continue
        rel = path.relative_to(VI)
        lines.extend(
            [
                f"## {path.stem.replace('-national-training-team-collection', '')}",
                "",
                f"Source translation: `{rel}`",
                "",
                "| Status | Page | Article | Author |",
                "| --- | ---: | --- | --- |",
            ]
        )
        body = body_after_toc(text)
        for page, title, author in rows:
            status = "started" if article_started(title, body) else "todo"
            total += 1
            started += status == "started"
            lines.append(f"| {status} | {page} | {title} | {author} |")
        lines.append("")
    lines.insert(4, f"- Articles started: {started}")
    lines.insert(5, f"- Articles total: {total}")
    lines.insert(6, "")
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
